/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AlchemistAcademyInterface extends ethers.utils.Interface {
  functions: {
    "alchemist(address,address,string)": FunctionFragment;
    "getLatestAlchemist()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "alchemist",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestAlchemist",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "alchemist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAlchemist",
    data: BytesLike
  ): Result;

  events: {};
}

export class AlchemistAcademy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AlchemistAcademyInterface;

  functions: {
    alchemist(
      _Chyme: string,
      _priceOracle: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLatestAlchemist(overrides?: CallOverrides): Promise<[string]>;
  };

  alchemist(
    _Chyme: string,
    _priceOracle: string,
    _symbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLatestAlchemist(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    alchemist(
      _Chyme: string,
      _priceOracle: string,
      _symbol: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getLatestAlchemist(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    alchemist(
      _Chyme: string,
      _priceOracle: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLatestAlchemist(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    alchemist(
      _Chyme: string,
      _priceOracle: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLatestAlchemist(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
